//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFormsWithDbFirst.HeroModelDesigner
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HeroDbConnStr : DbContext
    {
        public HeroDbConnStr()
            : base("name=HeroDbConnStr")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Hero> Hero { get; set; }
        public virtual DbSet<HeroWeapon> HeroWeapon { get; set; }
        public virtual DbSet<Weapon> Weapon { get; set; }
    
        [DbFunction("HeroDbConnStr", "udf_favourite_weapon")]
        public virtual IQueryable<udf_favourite_weapon_Result> udf_favourite_weapon()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<udf_favourite_weapon_Result>("[HeroDbConnStr].[udf_favourite_weapon]()");
        }
    
        public virtual int CreateHero(string heroName)
        {
            var heroNameParameter = heroName != null ?
                new ObjectParameter("HeroName", heroName) :
                new ObjectParameter("HeroName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateHero", heroNameParameter);
        }
    
        public virtual int usp_GetFavouriteWeaponForUser(string heroName)
        {
            var heroNameParameter = heroName != null ?
                new ObjectParameter("heroName", heroName) :
                new ObjectParameter("heroName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_GetFavouriteWeaponForUser", heroNameParameter);
        }
    
        public virtual int usp_GetMostLikedWeaponForHero(string heroName)
        {
            var heroNameParameter = heroName != null ?
                new ObjectParameter("heroName", heroName) :
                new ObjectParameter("heroName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_GetMostLikedWeaponForHero", heroNameParameter);
        }
    
        public virtual ObjectResult<usp_GetMostLikedWeaponForHero1_Result> usp_GetMostLikedWeaponForHero1(string heroName)
        {
            var heroNameParameter = heroName != null ?
                new ObjectParameter("heroName", heroName) :
                new ObjectParameter("heroName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetMostLikedWeaponForHero1_Result>("usp_GetMostLikedWeaponForHero1", heroNameParameter);
        }
    }
}
